package com.conexaosolidaria.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AvaliacaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvaliacaoAllPropertiesEquals(Avaliacao expected, Avaliacao actual) {
        assertAvaliacaoAutoGeneratedPropertiesEquals(expected, actual);
        assertAvaliacaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvaliacaoAllUpdatablePropertiesEquals(Avaliacao expected, Avaliacao actual) {
        assertAvaliacaoUpdatableFieldsEquals(expected, actual);
        assertAvaliacaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvaliacaoAutoGeneratedPropertiesEquals(Avaliacao expected, Avaliacao actual) {
        assertThat(expected)
            .as("Verify Avaliacao auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvaliacaoUpdatableFieldsEquals(Avaliacao expected, Avaliacao actual) {
        assertThat(expected)
            .as("Verify Avaliacao relevant properties")
            .satisfies(e -> assertThat(e.getEstrelas()).as("check estrelas").isEqualTo(actual.getEstrelas()))
            .satisfies(e -> assertThat(e.getObservacao()).as("check observacao").isEqualTo(actual.getObservacao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvaliacaoUpdatableRelationshipsEquals(Avaliacao expected, Avaliacao actual) {
        assertThat(expected)
            .as("Verify Avaliacao relationships")
            .satisfies(e -> assertThat(e.getEvento()).as("check evento").isEqualTo(actual.getEvento()));
    }
}
