package com.conexaosolidaria.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InscricaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscricaoAllPropertiesEquals(Inscricao expected, Inscricao actual) {
        assertInscricaoAutoGeneratedPropertiesEquals(expected, actual);
        assertInscricaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscricaoAllUpdatablePropertiesEquals(Inscricao expected, Inscricao actual) {
        assertInscricaoUpdatableFieldsEquals(expected, actual);
        assertInscricaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscricaoAutoGeneratedPropertiesEquals(Inscricao expected, Inscricao actual) {
        assertThat(expected)
            .as("Verify Inscricao auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscricaoUpdatableFieldsEquals(Inscricao expected, Inscricao actual) {
        assertThat(expected)
            .as("Verify Inscricao relevant properties")
            .satisfies(e -> assertThat(e.getData()).as("check data").isEqualTo(actual.getData()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscricaoUpdatableRelationshipsEquals(Inscricao expected, Inscricao actual) {
        assertThat(expected)
            .as("Verify Inscricao relationships")
            .satisfies(e -> assertThat(e.getEvento()).as("check evento").isEqualTo(actual.getEvento()));
    }
}
